//! Export blueprints as cloud-init, shell, Packer HCL, and docs.

use vpsforge_blueprint::Blueprint;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportFormat {
    CloudInit,
    Shell,
    Packer,
    Docs,
}

impl ExportFormat {
    pub fn parse(value: &str) -> Option<Self> {
        match value.to_ascii_lowercase().as_str() {
            "cloud-init" | "cloudinit" => Some(Self::CloudInit),
            "shell" | "sh" | "bash" => Some(Self::Shell),
            "packer" | "hcl" => Some(Self::Packer),
            "docs" | "md" | "markdown" => Some(Self::Docs),
            _ => None,
        }
    }

    pub fn extension(self) -> &'static str {
        match self {
            Self::CloudInit => "cloud-init.yaml",
            Self::Shell => "sh",
            Self::Packer => "pkr.hcl",
            Self::Docs => "md",
        }
    }
}

pub fn export(blueprint: &Blueprint, format: ExportFormat) -> String {
    match format {
        ExportFormat::CloudInit => cloud_init(blueprint),
        ExportFormat::Shell => shell(blueprint),
        ExportFormat::Packer => packer(blueprint),
        ExportFormat::Docs => docs(blueprint),
    }
}

pub fn cloud_init(blueprint: &Blueprint) -> String {
    let packages = merged_packages(blueprint);
    let package_yaml = packages
        .iter()
        .map(|p| format!("  - {p}"))
        .collect::<Vec<_>>()
        .join("\n");
    let ports = blueprint
        .security
        .firewall
        .ports
        .iter()
        .map(|p| format!("  - '{p}'"))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"#cloud-config
# Generated by VPSForge from blueprint `{name}`
# This file is first-boot user-data. Review before launching an instance.

package_update: true
package_upgrade: true

packages:
{package_yaml}

runcmd:
  - [ sh, -c, "command -v vpsforge >/dev/null && vpsforge blueprint apply {name} --yes || echo 'Install vpsforge, then: vpsforge blueprint apply {name}'" ]

ssh_pwauth: {pw}
disable_root: {disable_root}

write_files:
  - path: /etc/vpsforge/blueprint-name
    content: {name}
    permissions: '0644'

final_message: "VPSForge blueprint {name} cloud-init finished. Firewall ports:\n{ports}"
"#,
        name = blueprint.name,
        pw = blueprint.security.ssh.password_authentication,
        disable_root = !blueprint.security.ssh.root_login,
    )
}

pub fn shell(blueprint: &Blueprint) -> String {
    let packages = merged_packages(blueprint).join(" ");
    let profiles = blueprint.expanded_profiles().join(" ");
    format!(
        r#"#!/usr/bin/env bash
# Generated by VPSForge from blueprint `{name}`
# Review this script. It never curls remote installers into bash.

set -euo pipefail

echo "VPSForge shell bootstrap: {name}"
echo "Profiles: {profiles}"

if command -v vpsforge >/dev/null 2>&1; then
  vpsforge detect
  vpsforge blueprint apply {name} --yes
  exit 0
fi

if command -v apt-get >/dev/null 2>&1; then
  sudo apt-get update
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends {packages}
elif command -v dnf >/dev/null 2>&1; then
  sudo dnf install -y {packages}
elif command -v pacman >/dev/null 2>&1; then
  sudo pacman -S --noconfirm --needed {packages}
else
  echo "Unsupported package manager. Install vpsforge and re-run." >&2
  exit 1
fi

echo "Bootstrap complete. Install the vpsforge binary for idempotent management."
"#,
        name = blueprint.name,
    )
}

pub fn packer(blueprint: &Blueprint) -> String {
    let packages = merged_packages(blueprint);
    let pkg_json = packages
        .iter()
        .map(|p| format!("\"{p}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        r#"# Generated by VPSForge from blueprint `{name}`
# HashiCorp Packer template for a reusable golden image.
# https://developer.hashicorp.com/packer

packer {{
  required_plugins {{
    qemu = {{
      source  = "github.com/hashicorp/qemu"
      version = ">= 1.1.0"
    }}
  }}
}}

variable "iso_url" {{
  type        = string
  description = "Installer ISO URL for the chosen Debian-family base"
}}

variable "iso_checksum" {{
  type        = string
  description = "Checksum of the installer ISO"
}}

source "qemu" "vpsforge" {{
  iso_url      = var.iso_url
  iso_checksum = var.iso_checksum
  output_directory = "output-{name}"
  disk_size    = "20000"
  memory       = 2048
  cpus         = 2
  headless     = true
  ssh_username = "vpsforge"
  ssh_timeout  = "20m"
}}

build {{
  name    = "{name}"
  sources = ["source.qemu.vpsforge"]

  provisioner "shell" {{
    inline = [
      "sudo apt-get update",
      "sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends {pkg_join}",
      "echo 'Blueprint {name} provisioned by VPSForge'"
    ]
  }}

  provisioner "file" {{
    content     = <<-EOT
{yaml}
EOT
    destination = "/tmp/{name}.yaml"
  }}

  post-processor "manifest" {{
    output = "manifest-{name}.json"
  }}
}}

# Logical packages encoded for documentation: [{pkg_json}]
"#,
        name = blueprint.name,
        pkg_join = packages.join(" "),
        yaml = serde_yaml::to_string(blueprint).unwrap_or_default(),
    )
}

pub fn docs(blueprint: &Blueprint) -> String {
    format!(
        r#"# Blueprint `{name}`

Generated by VPSForge.

## Requirements

- Memory: {mem}
- Architecture: {arch}
- Base family: {family}

## Profiles

{profiles}

## Packages

{packages}

## Security

- Password authentication: {pw}
- Root login: {root}
- Firewall: {fw} (ports {ports})

## Storage

- PostgreSQL: {pg}
- Redis: {redis}

## AI

- Ollama: {ollama}
- GPU: {gpu}

## Reproduction

```bash
vpsforge blueprint apply {name}
vpsforge blueprint export {name} --format cloud-init
vpsforge blueprint export {name} --format packer
```
"#,
        name = blueprint.name,
        mem = blueprint.requirements.memory,
        arch = blueprint.requirements.architecture.join(", "),
        family = blueprint.base.family,
        profiles = blueprint
            .profiles
            .iter()
            .map(|p| format!("- `{p}`"))
            .collect::<Vec<_>>()
            .join("\n"),
        packages = blueprint
            .packages
            .iter()
            .map(|p| format!("- `{p}`"))
            .collect::<Vec<_>>()
            .join("\n"),
        pw = blueprint.security.ssh.password_authentication,
        root = blueprint.security.ssh.root_login,
        fw = blueprint.security.firewall.enabled,
        ports = blueprint
            .security
            .firewall
            .ports
            .iter()
            .map(|p| p.to_string())
            .collect::<Vec<_>>()
            .join(", "),
        pg = blueprint.storage.postgres,
        redis = blueprint.storage.redis,
        ollama = blueprint.ai.ollama,
        gpu = blueprint.ai.gpu,
    )
}

fn merged_packages(blueprint: &Blueprint) -> Vec<String> {
    let mut pkgs = blueprint.packages.clone();
    if blueprint.services.docker.enabled {
        pkgs.push("docker.io".into());
    }
    if blueprint.services.nginx.enabled {
        pkgs.push("nginx".into());
    }
    if blueprint.storage.postgres {
        pkgs.push("postgresql".into());
    }
    if blueprint.storage.redis {
        pkgs.push("redis".into());
    }
    pkgs.sort();
    pkgs.dedup();
    pkgs
}

#[cfg(test)]
mod tests {
    use super::*;
    use vpsforge_blueprint::Blueprint;

    #[test]
    fn exports_are_non_empty() {
        let bp = Blueprint::template("ai-production");
        assert!(cloud_init(&bp).contains("#cloud-config"));
        assert!(shell(&bp).contains("set -euo pipefail"));
        assert!(packer(&bp).contains("provisioner"));
        assert!(docs(&bp).contains("Reproduction"));
    }
}
